apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    type: infrastructure
    app: cert-manager
spec:
  project: platform-tools

  sources:
    - repoURL: https://github.com/temitayocharles/helm-charts.git
      targetRevision: main
      ref: values
    
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.19.3
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/cert-manager/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
