apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: platform-tools

  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.19.3
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/temitayocharles/helm-charts/main/cert-manager/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
