apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  labels:
    type: infrastructure
    app: vault
spec:
  project: platform-tools
  
  sources:
    - repoURL: https://github.com/temitayocharles/helm-charts.git
      targetRevision: main
      ref: values
    
    - repoURL: https://helm.hashicorp.com
      chart: vault
      targetRevision: 0.27.0
      helm:
        releaseName: vault
        valueFiles:
          - $values/vault/values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
