apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: platform-tools
  
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.27.0
    helm:
      values: |
        server:
          dataStorage:
            enabled: true
            size: 10Gi
            storageClass: local-path
          
          auditStorage:
            enabled: true
            size: 5Gi
            storageClass: local-path
          
          ha:
            enabled: true
            replicas: 1
            raft:
              enabled: true
              setNodeId: true
          
          standalone:
            enabled: false
        
        injector:
          enabled: true
        
        ui:
          enabled: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
