apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: security

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: security-viewer
  namespace: security
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: security-viewer-binding
  namespace: security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: security-viewer
subjects:
- kind: ServiceAccount
  name: default
  namespace: security
