apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: platform-tools

  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 5.3.1
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/temitayocharles/helm-charts/main/velero/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: velero

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
