apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    type: observability
    app: loki
spec:
  project: platform-observability

  sources:
    - repoURL: https://github.com/temitayocharles/helm-charts.git
      targetRevision: main
      ref: values
    
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki-stack
      targetRevision: 2.10.2
      helm:
        releaseName: loki
        valueFiles:
          - $values/loki/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
