apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cila-health-monolith
  namespace: argocd
spec:
  project: workloads
  sources:
    - repoURL: https://github.com/temitayocharles/helm-charts.git
      targetRevision: main
      path: applications/cila-health-monolith
      helm:
        valueFiles:
          - $values/applications/cila-health/cila-health-monolith/values-staging.yaml
    - repoURL: https://github.com/temitayocharles/platform-gitops.git
      targetRevision: main
      ref: values
      path: applications/cila-health/cila-health-monolith
    - repoURL: https://github.com/temitayocharles/configurations.git
      targetRevision: main
      path: applications/cila-health-monolith/configmaps
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
