apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.51.0
    helm:
      values: |
        # Loki with local storage (development only)
        loki:
          enabled: true
          auth_enabled: false
          commonConfig:
            replication_factor: 1
            storage:
              type: filesystem
              filesystem:
                directory: /loki/chunks
            limits_config:
              retention_period: 168h
          storage:
            bucketNames:
              chunks: chunks
              rules: rules
              admin: admin
        
        minio:
          enabled: false
        
        read:
          replicas: 1
          persistence:
            enabled: true
            size: 5Gi
            storageClassName: local-path
        
        write:
          replicas: 1
          persistence:
            enabled: true
            size: 5Gi
            storageClassName: local-path
        
        backend:
          replicas: 1
          persistence:
            enabled: true
            size: 5Gi
            storageClassName: local-path
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
