apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security
  namespace: argocd
spec:
  project: platform-security
  
  source:
    repoURL: https://github.com/temitayocharles/platform-gitops.git
    targetRevision: main
    path: infrastructure/security
  
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
