apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads-root
  namespace: argocd
spec:
  project: workloads
  source:
    repoURL: https://github.com/temitayocharles/platform-gitops.git
    targetRevision: main
    path: applications/fintech
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
